[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "c20eb00dccab9493420b95fd4915d961940e34f2"
os = "macos"

    [[Ncurses.download]]
    sha256 = "931bbda155f58951a6a3ebfaeb5080c7d92eed49eb5a6f9751e69bd4ed704315"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.aarch64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "cc5027cb1425f5cb530b5dd53369cdb80f1e60a4"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "8a596ef5a53f127fa79da52f6f30ccd41033ab8b569d0497171079b67710b658"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.aarch64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "9d5257f8b7b295942e7fcd44b455b0a3b93805d8"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "3a1015611967c184760ae04803e76fcb3bb35f6c020c1cfedeabccb44c96b277"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.aarch64-linux-musl.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "b583b28776b2f0e6cf033fb5bcf24a6f045ac395"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "9162b95ac20a391cbd5fb4d40547634d5c57d58698c6f60cc20748afc0bc968b"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.aarch64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfbfd141b3d8d665a2af2de7e147bc2a056c1cff"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "7537969444f136a17e7e516377bdf8b1bd0a35e400ffe03a215d277ef9923cda"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.armv6l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6043241b3822a99f993e7676848d6392fdb4362f"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "5c72e5d4232bd132a2ef36ad3cc6304609aa95dc1e0979344bad007501339f68"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.armv6l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "472be9f9e752a46ef38e4f344b3a74ae90098b9d"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "e2caf09d9642fa32d5c8c625e225c195c8f89702a1c92abe3f989dbc9729b69d"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.armv7l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f733acb6b8fead925fa04bdda59463411956a2c"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "b6147779f9e5cb79f3915b46451c6eeacf7c0558300367f3e82b14b0b0a5fc14"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.armv7l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "fa10598b49a2bba2e076f0bcf28c2ab04ca70690"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "9e0907e748dee839faaa28e076ac03c9f1c57529c345916fa458da8918070d5c"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.i686-linux-gnu.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "01dc656ef10e03e911c30e78c4baecfd6ded036c"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "5ab7967ef7bea5056c8a481e08382fe7bf2a5b902d0fe8dd6651dad057140000"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.i686-linux-musl.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "427c34666ec29aaf5372b0ceae0642eb89f168d0"
os = "windows"

    [[Ncurses.download]]
    sha256 = "8fe3b06bbf0dc62051bc514b3fd4181aba64c4fc610a6ef2bf44991614ec9639"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.i686-w64-mingw32.tar.gz"
[[Ncurses]]
arch = "powerpc64le"
git-tree-sha1 = "d96835fb75dc17a19960dcdfe1f32753e9b88d4b"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "f7934beb44d8adbb3aa8a98ba99cd36c33289e70341297a1f7d53cfc84d490bf"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.powerpc64le-linux-gnu.tar.gz"
[[Ncurses]]
arch = "riscv64"
git-tree-sha1 = "d2f2b1c86754c5928fb5040ba5ba66232aaef1ef"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "6e480ab83f975613ec868d7d54e78ce3f4c47fa19380e81d17857a244858a405"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.riscv64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "35d559b154a1e7b4d51aae65e91ca44f7bc9761b"
os = "macos"

    [[Ncurses.download]]
    sha256 = "ed276b38093c343ffc8f0aa29768e4cd7554c98fe09feea02caa46510ffaae3e"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.x86_64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "ef00fd79126cf3faac9fbce599a27077b6b8e958"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "479d168ab9391933ad2b1c176e7a5c429e34d72166abd7c17947ba56117c600c"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.x86_64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "ab04154fdc34a06fa8d73863593f79168f2d8741"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "fa3d05ea9f01025d2d67dc817394a8a5cede07b1229507f394dfba070698d36b"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.x86_64-linux-musl.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "d4d13b0103ab063663553af77b8430d05f219b5f"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "494f8cf2beba7390df011e83475ade37324091995054899ddbd3963d41959702"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.x86_64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "91ef29f15adb500fd0886649e57f12005d00cfb8"
os = "windows"

    [[Ncurses.download]]
    sha256 = "2663d4d0c35f9a70a5bcdf415581aab2648e7de15f6ac5498ce8e311dd3175f7"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+2/Ncurses.v6.6.0.x86_64-w64-mingw32.tar.gz"
