[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "6ae8d0c0004aec1e4f2c2ed73a935ce9bc06fffb"
os = "macos"

    [[Ncurses.download]]
    sha256 = "7bfa7fad87a3efa3498852b542a4210daf9bfad0f114a651aa18a54a5cfeba05"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.aarch64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "d47b16836ed3849c8ffab1ec65865533ecee6727"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "23bc3587860fc7af4e1e8efb37d2e9a2cf7ee89d2fcdbdc680eed3b79131f5e4"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.aarch64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "ed47430583e8669c5af6260903600737c58e94d7"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "ba58330a2c7a0821accef1bd5da324dd8c73899ce998f71331778e830eb83252"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.aarch64-linux-musl.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "3f1560a8655221a653d030a38743083a87d6d62b"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "edd24936e73e8a9c2099bac0c666bde0973605a2405e9ee2ca81eb1e354259b4"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.aarch64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08186305910cc995e4f9adfdac7bdddc279cfa06"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "29e704e3ca92939a84cc72278e59f547c170a6b7189fd1a85aa276d331f99ceb"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.armv6l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "868a2fcc76950214433117a4a2f2bf0aeda9f3ca"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "f49b9ec3ce4d46561760b495e867880cd0bd3a2d3dcabe129a3ffe6aee046717"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.armv6l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "743d38f7cde6c1c31898b0fa4e2d0465ac7d545c"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "e5c863b20f9c6160764158bfe49bb53d4628e08e8a084452a7845867a9d9a9ed"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.armv7l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "16da78bfbd886e5ed189299bf862962d37e7645a"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "eab5e4e4773c9939d15b4accaf5f5a11af35e6cbdddc6824e5e145bf9022996f"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.armv7l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "54b66ed952db8496f0c5bb4e01d46a83f7821d7f"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "d9ce707d41727f7991800f8dd8a0b7b39546e63a3e765ad9998aea1f52f72dbf"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.i686-linux-gnu.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "d4e18dae89354793f63bdc1e71d5ee0c3f20710c"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "fe783f84ff48966c9a80f9f312253705407323fea6313da1a523531299487406"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.i686-linux-musl.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "d2618d862cf2cf3fab563515d97e06702f7a1817"
os = "windows"

    [[Ncurses.download]]
    sha256 = "f2fbeaa3742fab25abcc3e53d8e6c6590ff09f51e7d9b2257ec40b3d6773e2aa"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.i686-w64-mingw32.tar.gz"
[[Ncurses]]
arch = "powerpc64le"
git-tree-sha1 = "f9b401e89a54a8d439f945872817771f9111cbb7"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "18ab2952d641b66cfa0ef4aee9d08b0e5360fb9a05f179995729c0a53a91a106"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.powerpc64le-linux-gnu.tar.gz"
[[Ncurses]]
arch = "riscv64"
git-tree-sha1 = "a4b28ea35a5d7fafe116535f06b7f52a86ce4b7e"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "e5e216a92a1696967e9952cc2eb12a5e125a56d1428ea0077150572ff79d75cd"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.riscv64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "6602c055761315e26e2ec2848420c99d53aee2f8"
os = "macos"

    [[Ncurses.download]]
    sha256 = "774030ba97646b2ff78cb67ac79cfbf4880be0c973992534f9469d7648bf5807"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.x86_64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "cf1eff099d84bdbebc68ba4f3f98105b06dfe2f3"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "4225102ef75022674f778397b94f843d57868865ec1d3e21a7e1ec9621b7d15e"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.x86_64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "e44ec3a2a3614c2dcc1c380c25dafe0bf8cd7a3b"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "4e89e260ea76f90e384c2665532f98de5bb0627b8fcb5cc64ba861df1fd4d99d"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.x86_64-linux-musl.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "93c2b7f10f559f92a31c075afad22676e83eb890"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "13f4621ca547e454395d2478d2a4164f01346c8df914714e7db37aa7451d4c07"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.x86_64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "684c590b2c2b5d97bb8019ef5a5451b2f1fbccd9"
os = "windows"

    [[Ncurses.download]]
    sha256 = "c0e8aacc5df845721dc5773470fc1430f3d3b0475cb1763f0e0037923de76d2b"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+0/Ncurses.v6.6.0.x86_64-w64-mingw32.tar.gz"
