[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "4873eee47477db2433ee7f06162b5d505a0195e8"
os = "macos"

    [[Ncurses.download]]
    sha256 = "107f29d1d304e8a168df3bcd1e7349db34f6e4f6265e90900260e039f7654542"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.aarch64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "ad330a8630ed1734c8c6efdb3c6e22442ba16ac8"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "3f04440b59a64a1bac6f0bcec5a0ce3ec16159ff68c6695b9f9238ddba0edeee"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.aarch64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "0aa920632a95c06142fbb66b207dfde0a45f2c15"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "72a157f62b5b924ae9c1a5b1f3690b77ccf1b1d334998d275519e902b09a7c56"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.aarch64-linux-musl.tar.gz"
[[Ncurses]]
arch = "aarch64"
git-tree-sha1 = "96a01b7a2eb999429f992599289096b00f69b52d"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "bd51bcd70f6c5964bffd1db1e473e2aa9898acc9304cea7ac51c62b634466800"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.aarch64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3296e36dd0a90427fc387aad2e9bb87c3d264656"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "1c7b7bb1fdc0b1207a8532a36f4a5fc91ae12d7b8f916b5d7e2ca5b550586e2c"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.armv6l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d176c497a40a390ed69cb10eb880ed5dbf322c02"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "fdf18e3289c8bfc3ef67aec84f2c1afdffef028c333df78b4402a9963fa2eb32"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.armv6l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b26e65b2e944a5cca789af45d189b464f82aa184"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "8b32c70e32f3cc7bce59047c2180c293414e9187d46b03b6b7906b1b097f1eee"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.armv7l-linux-gnueabihf.tar.gz"
[[Ncurses]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c92bf583b2ea303b49b11e5633304dfc743d486f"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "17a5839a18cd565fd783795e80b49215c18f5922fddf2a544cfbcca7fcdd01b3"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.armv7l-linux-musleabihf.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "2d2b4d2eef864a8efaf58f338c95b93877d8b3d4"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "9543e75c9d28b279f0693293dfa6bbfe05178e7f3648a7793ebb2be22cbef6d2"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.i686-linux-gnu.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "666754927960b677f1e1a85db4862d1fa453c2a7"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "64de06b93c30f7a6d8836f4755ed35e672d7c68df016ea76bbddb23b3fb4b862"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.i686-linux-musl.tar.gz"
[[Ncurses]]
arch = "i686"
git-tree-sha1 = "8cf24709b5d9a071c26a7c33fc0161f30ec99192"
os = "windows"

    [[Ncurses.download]]
    sha256 = "ea59a14796b8c7663952bda244b4a6754d337ecc8fdc8d7c22c23ce51d5a37dd"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.i686-w64-mingw32.tar.gz"
[[Ncurses]]
arch = "powerpc64le"
git-tree-sha1 = "7abd712519c39b889f2d34d5110b1723f8212eef"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "c1f336898eb7462e11874e406016b1734aade69fbb14d049a0efefb9b9da6459"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.powerpc64le-linux-gnu.tar.gz"
[[Ncurses]]
arch = "riscv64"
git-tree-sha1 = "d2f2b1c86754c5928fb5040ba5ba66232aaef1ef"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "6e480ab83f975613ec868d7d54e78ce3f4c47fa19380e81d17857a244858a405"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.riscv64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "fe7716c166ac50a127bebd41b722c4dce72e1ef5"
os = "macos"

    [[Ncurses.download]]
    sha256 = "bc92264892ed2368ac59c040cadea7612601186ec277284dc5a844ac2bf36271"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.x86_64-apple-darwin.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "a5a418589b417c54efadea19e0b74331ae810174"
libc = "glibc"
os = "linux"

    [[Ncurses.download]]
    sha256 = "3a110a872ed9d61375f4851ec47691071f5365974ca995ef76bbe091ef82059c"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.x86_64-linux-gnu.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "b87b9da4d4e9c5a0b98bc5c8fa25730fd2997fea"
libc = "musl"
os = "linux"

    [[Ncurses.download]]
    sha256 = "770c113456e77e5998510cdd7e35ba6221813d9f15b8414fd0a4df9c86b2660a"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.x86_64-linux-musl.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "6eadd9ccb15b1124dacd8d08ebc5a7d0d6de1c31"
os = "freebsd"

    [[Ncurses.download]]
    sha256 = "c29c90acdd43150b0d5e686d83ecf7e844ac0450ee62303d910600454d849a03"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.x86_64-unknown-freebsd.tar.gz"
[[Ncurses]]
arch = "x86_64"
git-tree-sha1 = "339008d3c4cfcdc0a7620f4407c755a005ba7282"
os = "windows"

    [[Ncurses.download]]
    sha256 = "e94df35f2369c7207adec2b74c1e9c2465a2db180a28d660c7008f5a588267d9"
    url = "https://github.com/JuliaBinaryWrappers/Ncurses_jll.jl/releases/download/Ncurses-v6.6.0+1/Ncurses.v6.6.0.x86_64-w64-mingw32.tar.gz"
